import { expect, test } from '@playwright/test';
import { capture, snapshot, start } from './controls';
import { LEADERBOARD_KEY } from '../../src/game/leaderboard';

test('正式生存：固定入口、追击攻击扣血、暂停冻结、零血结算与满血重开', async ({ page }) => {
  test.setTimeout(120000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await start(page, 'survival');
  await expect.poll(async () => (await snapshot(page)).totalSpawned, { timeout: 18000 }).toBeGreaterThanOrEqual(9);
  const initial = await snapshot(page);
  expect(new Set(initial.targets.map(z => z.spawnZone)).size).toBe(6);
  expect(initial.targets.some(z => z.kind === 'cone')).toBe(true);
  expect(initial.targets.some(z => z.kind === 'bucket')).toBe(true);
  expect(initial.blockedZombies).toEqual([]);
  await page.screenshot({ path: 'test-results/survivor-gameplay.png' });
  const first = initial.targets[0];
  await expect.poll(async () => {
    const s = await snapshot(page), z = s.targets.find(z => z.id === first.id)!;
    return Math.hypot(z.x - s.player.x, z.z - s.player.z);
  }).toBeLessThan(Math.hypot(first.x, first.z - 9));
  await expect.poll(async () => (await snapshot(page)).health, { timeout: 65000 }).toBeLessThan(100);
  const hurt = await snapshot(page);
  expect(hurt.phase).toBe('playing');
  expect(hurt.targets.some(z => z.attacking && z.attackTime > 0)).toBe(true);
  expect(hurt.nearest).toBeCloseTo(1.25, 4);
  await expect(page.getByTestId('player-health')).not.toHaveText('100');
  await page.screenshot({ path: 'test-results/survivor-attack.png' });
  await page.keyboard.press('Escape');
  const paused = await snapshot(page); await page.waitForTimeout(500);
  const frozen = await snapshot(page);
  expect(frozen.health).toBe(paused.health); expect(frozen.survived).toBe(paused.survived);
  expect(frozen.targets).toEqual(paused.targets);
  await page.getByRole('button', { name: '继续游戏' }).click(); await capture(page);
  await expect(page.getByRole('region', { name: '游戏结束' })).toBeVisible({ timeout: 35000 });
  const ended = await snapshot(page);
  expect(ended.health).toBe(0); expect(ended.pointerLocked).toBe(false);
  const stored = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), LEADERBOARD_KEY);
  expect(stored[0].id).toBe(ended.result!.id);
  await page.screenshot({ path: 'test-results/survivor-result.png' });
  await page.getByRole('button', { name: '再守一次' }).click(); await capture(page);
  const reset = await snapshot(page);
  expect(reset.health).toBe(100); expect(reset.player).toEqual({ x: 0, z: 9 });
  expect(reset.shots).toBe(0); expect(reset.breach).toBeNull();
  await page.keyboard.press('Escape'); await page.getByRole('button', { name: '返回主菜单' }).click();
  await page.reload(); await page.getByRole('button', { name: '查看排行榜' }).click();
  await expect(page.getByRole('row')).toHaveCount(2);
  expect(errors).toEqual([]);
});
